document.writeln("<table border=\"1\" width=\"100%\">");
document.writeln("");
document.writeln("");
document.writeln("            <tbody>");
document.writeln("");
document.writeln("");
document.writeln("            <tr>");
document.writeln("");
document.writeln("");
document.writeln("                <td align=\"center\" bgcolor=\"#ff0000\" height=\"45\"><p style=\"line-height:200%\"><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"color:#fff;font-family:微软雅黑\">澳门开奖网91</span><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"font-family:微软雅黑;color:#0ff\">5252</span><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"color:#0ff;font-family:微软雅黑\">.com</span><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"color:#ff0;font-family:微软雅黑\">⑥肖&#9329;码</span></p></td>");
document.writeln("");
document.writeln("");
document.writeln("            </tr>");
document.writeln("");
document.writeln("");
document.writeln("            <tr>");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\">");
document.writeln("				<span style=\"color:#00f\">117期</span><span");
document.writeln("                        style=\"color:red\">【⑥肖&#9329;码】<span style=\"color:#00f\">造福彩民</span></span><span");
document.writeln("                        style=\"color:#000\"><br>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#fff\">马【09.21.45】虎【13.37.49】<br></span><span");
document.writeln("                        style=\"background-color:#fff\">兔【12.24.36】</span></span><span");
document.writeln("                        style=\"background-color:#FFFF00\"><font color=\"#FF0000\">猪</font></span><span");
document.writeln("                        style=\"color:#000; background-color:#fff\">【04.</span><font color=\"#FF0000\"><span");
document.writeln("                        style=\"background-color:#FFFF00\">16</span></font><span");
document.writeln("                        style=\"color:#000; background-color:#fff\">.40】<br></span>");
document.writeln("				<span");
document.writeln("                        style=\"color:#000\"><span");
document.writeln("                        style=\"background-color:#fff\">狗【05.17.29】牛【02.14.38】<br></span></span>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#FFFF00;color:#FF0000\">开奖结果：猪16准</span><span style=\"color:red\"><span");
document.writeln("                        style=\"background-color:#ff0\"><br></span><span");
document.writeln("                        style=\"background-color:#fff\">澳门开奖网</span></span><span style=\"background-color:#fff\"><span");
document.writeln("                        style=\"color: #0000FF\">91</span><span style=\"color:red\">5252</span><span");
document.writeln("                        style=\"color:#00f\">.com</span><span style=\"color:red\">造福全网彩民</span></span></p></td>");
document.writeln("");
document.writeln("            </tr>");
document.writeln("            <tr>");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\">");
document.writeln("				<span style=\"color:#00f\">118期</span><span");
document.writeln("                        style=\"color:red\">【⑥肖&#9329;码】<span style=\"color:#00f\">造福彩民</span></span><span");
document.writeln("                        style=\"color:#000\"><br>");
document.writeln("				</span>");
document.writeln("				<font color=\"#FF0000\">");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#FFFF00\">蛇</span></font><span");
document.writeln("                        style=\"color:#000\"><span");
document.writeln("                        style=\"background-color:#fff\">【10.22.</span></span><span");
document.writeln("                        style=\"background-color:#FFFF00\"><font color=\"#FF0000\">34</font></span><span");
document.writeln("                        style=\"color:#000; background-color:#fff\">】虎【13.37.49】<br></span>");
document.writeln("				<span");
document.writeln("                        style=\"color:#000\"><span");
document.writeln("                        style=\"background-color:#fff\">兔【12.24.36】马【09.21.33】<br></span><span");
document.writeln("                        style=\"background-color:#fff\">狗【05.17.29】牛【02.14.26】<br></span></span>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#FFFF00;color:#FF0000\">开奖结果：蛇34准</span><span style=\"color:red\"><span");
document.writeln("                        style=\"background-color:#ff0\"><br></span><span");
document.writeln("                        style=\"background-color:#fff\">澳门开奖网</span></span><span style=\"background-color:#fff\"><span");
document.writeln("                        style=\"color: #0000FF\">91</span><span style=\"color:red\">5252</span><span");
document.writeln("                        style=\"color:#00f\">.com</span><span style=\"color:red\">造福全网彩民</span></span></p></td>");
document.writeln("");
document.writeln("            </tr>");
document.writeln("            <tr>");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\">");
document.writeln("				<span style=\"color:#00f\">121期</span><span");
document.writeln("                        style=\"color:red\">【⑥肖&#9329;码】<span style=\"color:#00f\">造福彩民</span></span><span");
document.writeln("                        style=\"color:#000\"><br>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#fff\">鼠【03.15.39】虎【01.37.49】<br></span></span>");
document.writeln("				<font color=\"#FF0000\">");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#FFFF00\">兔</span></font><span");
document.writeln("                        style=\"color:#000\"><span");
document.writeln("                        style=\"background-color:#fff\">【12.24.</span></span><span");
document.writeln("                        style=\"background-color:#FFFF00\"><font color=\"#FF0000\">36</font></span><span");
document.writeln("                        style=\"color:#000; background-color:#fff\">】龙【11.23.35】<br></span>");
document.writeln("				<span");
document.writeln("                        style=\"color:#000\"><span");
document.writeln("                        style=\"background-color:#fff\">狗【05.17.29】牛【02.14.26】<br></span></span>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#FFFF00;color:#FF0000\">开奖结果：兔36准</span><span style=\"color:red\"><span");
document.writeln("                        style=\"background-color:#ff0\"><br></span><span");
document.writeln("                        style=\"background-color:#fff\">澳门开奖网</span></span><span style=\"background-color:#fff\"><span");
document.writeln("                        style=\"color: #0000FF\">91</span><span style=\"color:red\">5252</span><span");
document.writeln("                        style=\"color:#00f\">.com</span><span style=\"color:red\">造福全网彩民</span></span></p></td>");
document.writeln("");
document.writeln("            </tr>");
document.writeln("            <tr>");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\">");
document.writeln("				<span style=\"color:#00f\">122期</span><span");
document.writeln("                        style=\"color:red\">【⑥肖&#9329;码】<span style=\"color:#00f\">造福彩民</span></span><span");
document.writeln("                        style=\"color:#000\"><br>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#fff\">鸡【06.18.30】虎【25.37.49】<br></span><span");
document.writeln("                        style=\"background-color:#fff\">蛇【10.22.34】龙【11.23.47】<br></span><span");
document.writeln("                        style=\"background-color:#fff\">狗【05.17.29】猪【04.16.40】<br></span></span>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#FFFF00;color:#FF0000\">开奖结果：？00准</span><span style=\"color:red\"><span");
document.writeln("                        style=\"background-color:#ff0\"><br></span><span");
document.writeln("                        style=\"background-color:#fff\">澳门开奖网</span></span><span style=\"background-color:#fff\"><span");
document.writeln("                        style=\"color: #0000FF\">91</span><span style=\"color:red\">5252</span><span");
document.writeln("                        style=\"color:#00f\">.com</span><span style=\"color:red\">造福全网彩民</span></span></p></td>");
document.writeln("");
document.writeln("            </tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("            </tbody>");
document.writeln("");
document.writeln("");
document.writeln("        </table>");