document.writeln("<div class=\"content-item\">");
document.writeln("");
document.writeln("");
document.writeln("    <div id=\"stsem\" class=\"text-bt\">");
document.writeln("");
document.writeln("");
document.writeln("        <table border=\"1\" width=\"100%\">");
document.writeln("");
document.writeln("");
document.writeln("            <tbody>");
document.writeln("");
document.writeln("");
document.writeln("            <tr>");
document.writeln("");
document.writeln("");
document.writeln("                <td align=\"center\" bgcolor=\"#ff0000\" height=\"45\"><p style=\"line-height:200%\"><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"color:#fff;font-family:微软雅黑\">澳门开奖网91</span><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"font-family:微软雅黑;color:#0ff\">5252</span><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"color:#0ff;font-family:微软雅黑\">.com</span><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"color:#ff0;font-family:微软雅黑\">⑤头综合</span></p></td>");
document.writeln("");
document.writeln("");
document.writeln("            </tr>");
document.writeln("");
document.writeln("  ");
document.writeln("		<tr>");
document.writeln("			<td>");
document.writeln("				<p align=\"center\"><font color=\"#FF0000\"><b>2022年</b></font><font><b><font color=\"#0000FF\">综合头数统计</font></b>");
document.writeln("				</font>");
document.writeln("			</td>");
document.writeln("		</tr>");
document.writeln("		<tr>");
document.writeln("			<td>");
document.writeln("				<font color=\"#0000FF\">0头:已连开</font><font color=\"#FF0000\">00</font><font color=\"#0000FF\">期,最高连开</font><font  color=\"#FF0000\">03</font><font  color=\"#0000FF\">期<br>0头:已</font><font  color=\"#FF0000\">08</font><font  color=\"#0000FF\">期未开,最高</font><font  color=\"#FF0000\">32</font><font  color=\"#0000FF\">期未开</font></td>");
document.writeln("		</tr>");
document.writeln("		<tr>");
document.writeln("			<td>");
document.writeln("				<font  color=\"#0000FF\">1头:已连开</font><font  color=\"#FF0000\">00</font><font  color=\"#0000FF\">期,最高连开</font><font  color=\"#FF0000\">05</font><font  color=\"#0000FF\">期<br>");
document.writeln("				1头:已</font><font  color=\"#FF0000\">04</font><font  color=\"#0000FF\">期未开,最高</font><font  color=\"#FF0000\">43</font><font  color=\"#0000FF\">期未开</font></td>");
document.writeln("		</tr>");
document.writeln("		<tr>");
document.writeln("			<td>");
document.writeln("				<font  color=\"#0000FF\">2头:已连开</font><font  color=\"#FF0000\">00</font><font  color=\"#0000FF\">期,最高连开</font><font  color=\"#FF0000\">02</font><font  color=\"#0000FF\">期<br>");
document.writeln("				2头:已</font><font  color=\"#FF0000\">07</font><font  color=\"#0000FF\">期未开,最高</font><font  color=\"#FF0000\">22</font><font  color=\"#0000FF\">期未开</font></td>");
document.writeln("		</tr>");
document.writeln("		<tr>");
document.writeln("			<td>");
document.writeln("				<font  color=\"#0000FF\">3头:已连开</font><font  color=\"#FF0000\">04</font><font  color=\"#0000FF\">期,最高连开</font><font  color=\"#FF0000\">04</font><font  color=\"#0000FF\">期<br>");
document.writeln("				3头:已</font><font  color=\"#FF0000\">00</font><font  color=\"#0000FF\">期未开,最高</font><font  color=\"#FF0000\">23</font><font  color=\"#0000FF\">期未开</font></td>");
document.writeln("		</tr>");
document.writeln("		<tr>");
document.writeln("			<td>");
document.writeln("				<font  color=\"#0000FF\">4头:已连开</font><font  color=\"#FF0000\">00</font><font  color=\"#0000FF\">期,最高连开</font><font  color=\"#FF0000\">02</font><font  color=\"#0000FF\">期<br>");
document.writeln("				4头:已</font><font  color=\"#FF0000\">05</font><font  color=\"#0000FF\">期未开,最高</font><font  color=\"#FF0000\">20</font><font  color=\"#0000FF\">期未开</font></td>");
document.writeln("		</tr>");
document.writeln("	</tbody>");
document.writeln("</table>");
document.writeln("");
document.writeln("    </div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</div>");
document.writeln("");
document.writeln("");
document.writeln("<div class=\"content-item\">");
document.writeln("");
document.writeln("");
document.writeln("    <div id=\"ytwm\" class=\"text-bt\"><span style=\"font-family:微软雅黑\"></span>");
document.writeln("");
document.writeln("");
document.writeln("        <table border=\"1\" width=\"100%\">");
document.writeln("");
document.writeln("");
document.writeln("            <tbody>");
document.writeln("");
document.writeln("");
document.writeln("            <tr>");
document.writeln("");
document.writeln("");
document.writeln("                <td bgcolor=\"#ff0000\" height=\"45\"><p style=\"line-height:200%;word-spacing:1px\" align=\"center\"><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"color:#fff;font-family:微软雅黑\">澳门开奖网91</span><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"font-family:微软雅黑;color:#0ff\">5252</span><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"color:#0ff;font-family:微软雅黑\">.com</span><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"color:#ff0;font-family:微软雅黑\">平特一肖</span></p></td>");
document.writeln("");
document.writeln("");
document.writeln("            </tr>");
document.writeln("");
document.writeln("");
document.writeln("            <tr>");
document.writeln("                <td align=\"center\" bgcolor=\"#ffffff\" height=\"45\"><p style=\"line-height:200%;word-spacing:1px\"");
document.writeln("                                                                    align=\"center\">");
document.writeln("				<span style=\"font-family: 微软雅黑; color: #0000FF\">122期</span><span style=\"color:red\">三字平特<span");
document.writeln("                        style=\"color:#000\">【小白鼠】开:？00中</span></span></span></p></td>");
document.writeln("");
document.writeln("            </tr>");
document.writeln("            <tr>");
document.writeln("                <td align=\"center\" bgcolor=\"#ffffff\" height=\"45\"><p style=\"line-height:200%;word-spacing:1px\"");
document.writeln("                                                                    align=\"center\">");
document.writeln("				<span style=\"font-family: 微软雅黑; color: #0000FF\">123期</span><span style=\"color:red\">三字平特<span");
document.writeln("                        style=\"color:#000\">【备料中】开:？00中</span></span></span></p></td>");
document.writeln("");
document.writeln("            </tr>");
document.writeln("            <tr>");
document.writeln("                <td align=\"center\" bgcolor=\"#ffffff\" height=\"45\"><p style=\"line-height:200%;word-spacing:1px\"");
document.writeln("                                                                    align=\"center\">");
document.writeln("				<span style=\"font-family: 微软雅黑; color: #0000FF\">124期</span><span style=\"color:red\">三字平特<span");
document.writeln("                        style=\"color:#000\">【备料中】开:？00中</span></span></span></p></td>");
document.writeln("");
document.writeln("            </tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("            <tr>");
document.writeln("");
document.writeln("");
document.writeln("                <td align=\"center\" bgcolor=\"#ffffff\" height=\"45\"><p style=\"line-height:200%;word-spacing:1px\"");
document.writeln("");
document.writeln("");
document.writeln("                                                                    align=\"center\"><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"color:red;font-family:微软雅黑\">澳门开奖网</span><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"color:#0000FF;font-family:微软雅黑\">91</span><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"color:red;font-family:微软雅黑\">5252</span><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"color:#00f;font-family:微软雅黑\">.com</span><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"color:red;font-family:微软雅黑\">数钱数到手抽筋</span></p></td>");
document.writeln("");
document.writeln("");
document.writeln("            </tr>");
document.writeln("");
document.writeln("");
document.writeln("            </tbody>");
document.writeln("");
document.writeln("");
document.writeln("        </table>");
document.writeln("");
document.writeln("");
document.writeln("    </div>");
document.writeln("");
document.writeln("");
document.writeln("    </div>");
document.writeln("");
document.writeln("");
document.writeln("<div class=\"content-item\">");
document.writeln("");
document.writeln("");
document.writeln("    <div id=\"stsem\" class=\"text-bt\">");
document.writeln("");
document.writeln("");
document.writeln("        <table border=\"1\" width=\"100%\">");
document.writeln("");
document.writeln("");
document.writeln("            <tbody>");
document.writeln("");
document.writeln("");
document.writeln("            <tr>");
document.writeln("");
document.writeln("");
document.writeln("                <td align=\"center\" bgcolor=\"#ff0000\" height=\"45\"><p style=\"line-height:200%\"><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"color:#fff;font-family:微软雅黑\">澳门开奖网91</span><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"font-family:微软雅黑;color:#0ff\">5252</span><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"color:#0ff;font-family:微软雅黑\">.com</span><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"color:#ff0;font-family:微软雅黑\">一波六码</span></p></td>");
document.writeln("");
document.writeln("");
document.writeln("            </tr>");
document.writeln("");
document.writeln("");
document.writeln("             <tr>");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\">");
document.writeln("				<span style=\"color: #0000FF\">106</span><span style=\"color:#00f\">期</span><span");
document.writeln("                        style=\"color:red\">【一波主六码】</span><span style=\"color:#000\"><br>");
document.writeln("				</span>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#FFFF00\"><font color=\"#FF0000\">");
document.writeln("				红波</font></span><span style=\"color:#000\"><span");
document.writeln("                        style=\"color:#000;background-color:#fff\">-【23.24.29.30.</span></span><span");
document.writeln("                        style=\"background-color:#FFFF00\"><font color=\"#FF0000\">34</font></span><span style=\"color:#000\"><span");
document.writeln("                        style=\"color:#000;background-color:#fff\">.35】</span><br></span>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#fff;color:#000\">");
document.writeln("				<span");
document.writeln("                        style=\"color:#000\">蓝波-【04.26.37.41.42.48】</span><br>开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">蛇34</span></font><span style=\"color:red\"><span");
document.writeln("                       style=\"background-color:#ff0\">准<br></span><span");
document.writeln("                        style=\"background-color:#fff\">澳门开奖网</span></span><span");
document.writeln("                        style=\"color: #0000FF; background-color: #FFFFFF\">91</span><span style=\"background-color:#fff\"><span");
document.writeln("                        style=\"color:red\">5252</span><span");
document.writeln("                        style=\"color:#00f\">.com</span><span style=\"color:red\">携手灭庄</span></span></p></td>");
document.writeln("            </tr>");
document.writeln("             <tr>");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\">");
document.writeln("				<span style=\"color: #0000FF\">107</span><span style=\"color:#00f\">期</span><span");
document.writeln("                        style=\"color:red\">【一波主六码】</span><span style=\"color:#000\"><br>");
document.writeln("				<span");
document.writeln("                        style=\"color:#000;background-color:#fff\">红波-【29.30.35.40.45.46】</span><br>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#FFFF00;color:#FF0000\">");
document.writeln("								蓝波</span><span");
document.writeln("                        style=\"background-color:#fff;color:#000\">-【</span><span");
document.writeln("                        style=\"background-color:#FFFF00;color:#FF0000\">14</span><span");
document.writeln("                        style=\"background-color:#fff;color:#000\">.20.25.41.42.48】</span></span><span");
document.writeln("                        style=\"background-color:#fff;color:#000\"><br>开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">牛14</span></font><span style=\"color:red\"><span");
document.writeln("                       style=\"background-color:#ff0\">准<br></span><span");
document.writeln("                        style=\"background-color:#fff\">澳门开奖网</span></span><span");
document.writeln("                        style=\"color: #0000FF; background-color: #FFFFFF\">91</span><span style=\"background-color:#fff\"><span");
document.writeln("                        style=\"color:red\">5252</span><span");
document.writeln("                        style=\"color:#00f\">.com</span><span style=\"color:red\">携手灭庄</span></span></p></td>");
document.writeln("            </tr>");
document.writeln("             <tr>");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\">");
document.writeln("				<span style=\"color: #0000FF\">109</span><span style=\"color:#00f\">期</span><span");
document.writeln("                        style=\"color:red\">【一波主六码】</span><span style=\"color:#000\"><br>");
document.writeln("				<span");
document.writeln("                        style=\"color:#FF0000;background-color:#FFFF00\">绿波</span><span");
document.writeln("                        style=\"color:#000;background-color:#fff\">-【32.33.38.39.</span></span><span");
document.writeln("                        style=\"background-color:#FFFF00\"><font color=\"#FF0000\">43</font></span><span style=\"color:#000\"><span");
document.writeln("                        style=\"color:#000;background-color:#fff\">.44】</span><br></span>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#fff;color:#000\">");
document.writeln("				<span");
document.writeln("                        style=\"color:#000\">蓝波-【20.36.41.42.47.48】</span><br>开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">猴43</span></font><span style=\"color:red\"><span");
document.writeln("                       style=\"background-color:#ff0\">准<br></span><span");
document.writeln("                        style=\"background-color:#fff\">澳门开奖网</span></span><span");
document.writeln("                        style=\"color: #0000FF; background-color: #FFFFFF\">91</span><span style=\"background-color:#fff\"><span");
document.writeln("                        style=\"color:red\">5252</span><span");
document.writeln("                        style=\"color:#00f\">.com</span><span style=\"color:red\">携手灭庄</span></span></p></td>");
document.writeln("            </tr>");
document.writeln("             <tr>");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\">");
document.writeln("				<span style=\"color: #0000FF\">110</span><span style=\"color:#00f\">期</span><span");
document.writeln("                        style=\"color:red\">【一波主六码】</span><span style=\"color:#000\"><br>");
document.writeln("				</span>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#FFFF00\"><font color=\"#FF0000\">");
document.writeln("				绿波</font></span><span style=\"color:#000\"><span");
document.writeln("                        style=\"color:#000;background-color:#fff\">-【11.</span></span><span");
document.writeln("                        style=\"background-color:#FFFF00\"><font color=\"#FF0000\">16</font></span><span style=\"color:#000\"><span");
document.writeln("                        style=\"color:#000;background-color:#fff\">.17.21.22.27】</span><br></span>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#fff;color:#000\">");
document.writeln("				<span");
document.writeln("                        style=\"color:#000\">红波-【29.30.34.35.40.45】</span><br>开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">猪16</span></font><span style=\"color:red\"><span");
document.writeln("                       style=\"background-color:#ff0\">准<br></span><span");
document.writeln("                        style=\"background-color:#fff\">澳门开奖网</span></span><span");
document.writeln("                        style=\"color: #0000FF; background-color: #FFFFFF\">91</span><span style=\"background-color:#fff\"><span");
document.writeln("                        style=\"color:red\">5252</span><span");
document.writeln("                        style=\"color:#00f\">.com</span><span style=\"color:red\">携手灭庄</span></span></p></td>");
document.writeln("            </tr>");
document.writeln("             <tr>");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\">");
document.writeln("				<span style=\"color: #0000FF\">112</span><span style=\"color:#00f\">期</span><span");
document.writeln("                        style=\"color:red\">【一波主六码】</span><span style=\"color:#000\"><br>");
document.writeln("				<span");
document.writeln("                        style=\"color:#FF0000;background-color:#FFFF00\">绿波</span><span");
document.writeln("                        style=\"color:#000;background-color:#fff\">-【05.06.11.17.</span></span><span");
document.writeln("                        style=\"background-color:#FFFF00\"><font color=\"#FF0000\">21</font></span><span style=\"color:#000\"><span");
document.writeln("                        style=\"color:#000;background-color:#fff\">.22】</span><br></span>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#fff;color:#000\">");
document.writeln("				<span");
document.writeln("                        style=\"color:#000\">红波-【02.07.08.12.13.40】</span><br>开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">马21</span></font><span style=\"color:red\"><span");
document.writeln("                       style=\"background-color:#ff0\">准<br></span><span");
document.writeln("                        style=\"background-color:#fff\">澳门开奖网</span></span><span");
document.writeln("                        style=\"color: #0000FF; background-color: #FFFFFF\">91</span><span style=\"background-color:#fff\"><span");
document.writeln("                        style=\"color:red\">5252</span><span");
document.writeln("                        style=\"color:#00f\">.com</span><span style=\"color:red\">携手灭庄</span></span></p></td>");
document.writeln("            </tr>");
document.writeln("             <tr>");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\">");
document.writeln("				<span style=\"color: #0000FF\">114</span><span style=\"color:#00f\">期</span><span");
document.writeln("                        style=\"color:red\">【一波主六码】</span><span style=\"color:#000\"><br>");
document.writeln("				</span>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#FFFF00\"><font color=\"#FF0000\">");
document.writeln("				绿波</font></span><span style=\"color:#000\"><span");
document.writeln("                        style=\"color:#000;background-color:#fff\">-【28.32.33.38.39.49】</span><br></span>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#fff;color:#000\">");
document.writeln("				<span");
document.writeln("                        style=\"color:#000\">红波-【13.18.19.23.24.29】</span><br>开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">鼠27</span></font><span style=\"color:red\"><span");
document.writeln("                       style=\"background-color:#ff0\">准<br></span><span");
document.writeln("                        style=\"background-color:#fff\">澳门开奖网</span></span><span");
document.writeln("                        style=\"color: #0000FF; background-color: #FFFFFF\">91</span><span style=\"background-color:#fff\"><span");
document.writeln("                        style=\"color:red\">5252</span><span");
document.writeln("                        style=\"color:#00f\">.com</span><span style=\"color:red\">携手灭庄</span></span></p></td>");
document.writeln("            </tr>");
document.writeln("             <tr>");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\">");
document.writeln("				<span style=\"color: #0000FF\">115</span><span style=\"color:#00f\">期</span><span");
document.writeln("                        style=\"color:red\">【一波主六码】</span><span style=\"color:#000\"><br>");
document.writeln("				<span");
document.writeln("                        style=\"color:#FF0000;background-color:#FFFF00\">绿波</span><span");
document.writeln("                        style=\"color:#000;background-color:#fff\">-【05.06.</span><span");
document.writeln("                        style=\"color:#FF0000;background-color:#FFFF00\">11</span><span");
document.writeln("                        style=\"color:#000;background-color:#fff\">.16.17.21】</span><br></span>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#fff;color:#000\">");
document.writeln("				<span");
document.writeln("                        style=\"color:#000\">红波-【19.23.24.29.30.34】</span><br>开：</span><span");
document.writeln("                        style=\"background-color:#FFFF00;color:#FF0000\">龙11</span><span style=\"color:red\"><span");
document.writeln("                       style=\"background-color:#ff0\">准<br></span><span");
document.writeln("                        style=\"background-color:#fff\">澳门开奖网</span></span><span");
document.writeln("                        style=\"color: #0000FF; background-color: #FFFFFF\">91</span><span style=\"background-color:#fff\"><span");
document.writeln("                        style=\"color:red\">5252</span><span");
document.writeln("                        style=\"color:#00f\">.com</span><span style=\"color:red\">携手灭庄</span></span></p></td>");
document.writeln("            </tr>");
document.writeln("             <tr>");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\">");
document.writeln("				<span style=\"color: #0000FF\">117</span><span style=\"color:#00f\">期</span><span");
document.writeln("                        style=\"color:red\">【一波主六码】</span><span style=\"color:#000\"><br>");
document.writeln("				</span>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#FFFF00\"><font color=\"#FF0000\">");
document.writeln("				绿波</font></span><span style=\"color:#000\"><span");
document.writeln("                        style=\"color:#000;background-color:#fff\">-【32.33.39.43.44.49】</span><br></span>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#fff;color:#000\">");
document.writeln("				<span");
document.writeln("                        style=\"color:#000\">蓝波-【03.04.09.10.14.20】</span><br>开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">猪16</span></font><span style=\"color:red\"><span");
document.writeln("                       style=\"background-color:#ff0\">准<br></span><span");
document.writeln("                        style=\"background-color:#fff\">澳门开奖网</span></span><span");
document.writeln("                        style=\"color: #0000FF; background-color: #FFFFFF\">91</span><span style=\"background-color:#fff\"><span");
document.writeln("                        style=\"color:red\">5252</span><span");
document.writeln("                        style=\"color:#00f\">.com</span><span style=\"color:red\">携手灭庄</span></span></p></td>");
document.writeln("            </tr>");
document.writeln("             <tr>");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\">");
document.writeln("				<span style=\"color: #0000FF\">119</span><span style=\"color:#00f\">期</span><span");
document.writeln("                        style=\"color:red\">【一波主六码】</span><span style=\"color:#000\"><br>");
document.writeln("				</span>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#FFFF00\"><font color=\"#FF0000\">");
document.writeln("				绿波</font></span><span style=\"color:#000\"><span");
document.writeln("                        style=\"color:#000;background-color:#fff\">-【06.11.17.21.22.27】</span><br></span>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#fff;color:#000\">");
document.writeln("				<span");
document.writeln("                        style=\"color:#000\">蓝波-【14.15.20.25.26.31】</span><br>开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">羊32</span></font><span style=\"color:red\"><span");
document.writeln("                       style=\"background-color:#ff0\">准<br></span><span");
document.writeln("                        style=\"background-color:#fff\">澳门开奖网</span></span><span");
document.writeln("                        style=\"color: #0000FF; background-color: #FFFFFF\">91</span><span style=\"background-color:#fff\"><span");
document.writeln("                        style=\"color:red\">5252</span><span");
document.writeln("                        style=\"color:#00f\">.com</span><span style=\"color:red\">携手灭庄</span></span></p></td>");
document.writeln("            </tr>");
document.writeln("             <tr>");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\">");
document.writeln("				<span style=\"color: #0000FF\">120</span><span style=\"color:#00f\">期</span><span");
document.writeln("                        style=\"color:red\">【一波主六码】</span><span style=\"color:#000\"><br>");
document.writeln("				</span>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#FFFF00\"><font color=\"#FF0000\">");
document.writeln("				绿波</font></span><span style=\"color:#000\"><span");
document.writeln("                        style=\"color:#000;background-color:#fff\">-【05.06.11.16.17.21】</span><br></span>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#fff;color:#000\">");
document.writeln("				<span");
document.writeln("                        style=\"color:#000\">红波-【29.30.34.35.40.45】</span><br>开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">羊32</span></font><span style=\"color:red\"><span");
document.writeln("                       style=\"background-color:#ff0\">准<br></span><span");
document.writeln("                        style=\"background-color:#fff\">澳门开奖网</span></span><span");
document.writeln("                        style=\"color: #0000FF; background-color: #FFFFFF\">91</span><span style=\"background-color:#fff\"><span");
document.writeln("                        style=\"color:red\">5252</span><span");
document.writeln("                        style=\"color:#00f\">.com</span><span style=\"color:red\">携手灭庄</span></span></p></td>");
document.writeln("            </tr>");
document.writeln("             <tr>");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\">");
document.writeln("				<span style=\"color: #0000FF\">122</span><span style=\"color:#00f\">期</span><span");
document.writeln("                        style=\"color:red\">【一波主六码】</span><span style=\"color:#000\"><br>");
document.writeln("				<span");
document.writeln("                        style=\"color:#000;background-color:#fff\">绿波-【33.38.39.43.44.49】</span><br></span>");
document.writeln("				<span");
document.writeln("                        style=\"background-color:#fff;color:#000\">");
document.writeln("				<span");
document.writeln("                        style=\"color:#000\">蓝波-【03.04.09.10.14.15】</span><br>开：</span><span style=\"color:red\"><span");
document.writeln("                       style=\"background-color:#ff0\"><span");
document.writeln("                        style=\"color:#000;background-color:#fff\">？00准</span><br></span><span");
document.writeln("                        style=\"background-color:#fff\">澳门开奖网</span></span><span");
document.writeln("                        style=\"color: #0000FF; background-color: #FFFFFF\">91</span><span style=\"background-color:#fff\"><span");
document.writeln("                        style=\"color:red\">5252</span><span");
document.writeln("                        style=\"color:#00f\">.com</span><span style=\"color:red\">携手灭庄</span></span></p></td>");
document.writeln("            </tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("            </tbody>");
document.writeln("");
document.writeln("");
document.writeln("        </table>");
document.writeln("");
document.writeln("");
document.writeln("        ");
document.writeln("");
document.writeln("");
document.writeln("        ");
document.writeln("");
document.writeln("");
document.writeln("    </div>");
document.writeln("");
document.writeln("");
document.writeln("</div>");
document.writeln("");
document.writeln("");
document.writeln("<div class=\"content-item\">");
document.writeln("");
document.writeln("");
document.writeln("    <div id=\"stsem\" class=\"text-bt\">");
document.writeln("");
document.writeln("");
document.writeln("        <table border=\"1\" width=\"100%\">");
document.writeln("");
document.writeln("");
document.writeln("            <tbody>");
document.writeln("");
document.writeln("");
document.writeln("            <tr>");
document.writeln("");
document.writeln("");
document.writeln("                <td align=\"center\" bgcolor=\"#ff0000\" height=\"45\"><p style=\"line-height:200%\"><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"color:#fff;font-family:微软雅黑\">澳门开奖网91</span><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"font-family:微软雅黑;color:#0ff\">5252</span><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"color:#0ff;font-family:微软雅黑\">.com</span><span");
document.writeln("");
document.writeln("");
document.writeln("                        style=\"color:#ff0;font-family:微软雅黑\">⑥尾&#9323;码</span></p></td>");
document.writeln("");
document.writeln("");
document.writeln("            </tr>");
document.writeln("");
document.writeln("");
document.writeln("              <tr> ");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\"><span style=\"color:#00f\">105期</span>");
document.writeln("                <span style=\"color:red\">【⑥尾&#9323;码】</span>");
document.writeln("                <span style=\"color:#000\">开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">蛇22准 ");
document.writeln("				</span></font>");
document.writeln("                <span style=\"color:#000\"> <br>");
document.writeln("                  0尾【10.30】</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">2尾</span></font><span style=\"color:#000\">【12.42】3尾【33.43】<br> ");
document.writeln("				  4尾【04.44】7尾【17.47】8尾【18.28】</span> <br>");
document.writeln("				  ");
document.writeln("              澳门开奖网 <span style=\"color: #0000FF\">91</span><span style=\"color:red\">5252</span><span style=\"color:#00f\">.com</span><span style=\"color:red\">全网至尊</span></p></td>");
document.writeln("            </tr>");
document.writeln("              <tr> ");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\"><span style=\"color:#00f\">106期</span>");
document.writeln("                <span style=\"color:red\">【⑥尾&#9323;码】</span>");
document.writeln("                <span style=\"color:#000\">开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">蛇34准</span></font><span style=\"color:#000\"> <br>");
document.writeln("                  0尾【20.30】2尾【32.42】</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">4尾</span></font><span style=\"color:#000\">【04.14】<br> ");
document.writeln("				  5尾【05.35】7尾【17.27】8尾【18.28】</span> <br>");
document.writeln("				  ");
document.writeln("              澳门开奖网 <span style=\"color: #0000FF\">91</span><span style=\"color:red\">5252</span><span style=\"color:#00f\">.com</span><span style=\"color:red\">全网至尊</span></p></td>");
document.writeln("            </tr>");
document.writeln("              <tr> ");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\"><span style=\"color:#00f\">107期</span>");
document.writeln("                <span style=\"color:red\">【⑥尾&#9323;码】</span>");
document.writeln("                <span style=\"color:#000\">开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">牛14准</span></font><span style=\"color:#000\"> <br>");
document.writeln("                  0尾【20.30】2尾【32.42】3尾【33.43】<br> ");
document.writeln("				  </span> <font color=\"#FF0000\">");
document.writeln("				<span style=\"background-color: #FFFF00\">4尾</span></font><span style=\"color:#000\">【34.44】7尾【17.47】8尾【18.48】</span> <br>");
document.writeln("				  ");
document.writeln("              澳门开奖网 <span style=\"color: #0000FF\">91</span><span style=\"color:red\">5252</span><span style=\"color:#00f\">.com</span><span style=\"color:red\">全网至尊</span></p></td>");
document.writeln("            </tr>");
document.writeln("              <tr> ");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\"><span style=\"color:#00f\">108期</span>");
document.writeln("                <span style=\"color:red\">【⑥尾&#9323;码】</span>");
document.writeln("                <span style=\"color:#000\">开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">猪40准</span></font><span style=\"color:#000\"> <br>");
document.writeln("                  </span> <font color=\"#FF0000\">");
document.writeln("				<span style=\"background-color: #FFFF00\">0尾</span></font><span style=\"color:#000\">【20.30】2尾【12.22】4尾【24.44】<br> ");
document.writeln("				  6尾【16.26】7尾【17.37】8尾【18.48】</span> <br>");
document.writeln("				  ");
document.writeln("              澳门开奖网 <span style=\"color: #0000FF\">91</span><span style=\"color:red\">5252</span><span style=\"color:#00f\">.com</span><span style=\"color:red\">全网至尊</span></p></td>");
document.writeln("            </tr>");
document.writeln("              <tr> ");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\"><span style=\"color:#00f\">110期</span>");
document.writeln("                <span style=\"color:red\">【⑥尾&#9323;码】</span>");
document.writeln("                <span style=\"color:#000\">开：猪16准 <br>");
document.writeln("                  0尾【20.40】1尾【11.31】4尾【14.44】<br> ");
document.writeln("				  </span> <font color=\"#FF0000\">");
document.writeln("				<span style=\"background-color: #FFFF00\">6尾</span></font><span style=\"color:#000\">【</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">16</span></font><span style=\"color:#000\">.26】7尾【17.37】9尾【09.19】</span> <br>");
document.writeln("				  ");
document.writeln("              澳门开奖网 <span style=\"color: #0000FF\">91</span><span style=\"color:red\">5252</span><span style=\"color:#00f\">.com</span><span style=\"color:red\">全网至尊</span></p></td>");
document.writeln("            </tr>");
document.writeln("              <tr> ");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\"><span style=\"color:#00f\">111期</span>");
document.writeln("                <span style=\"color:red\">【⑥尾&#9323;码】</span>");
document.writeln("                <span style=\"color:#000\">开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">蛇10准 ");
document.writeln("				</span></font>");
document.writeln("                <span style=\"color:#000\"> <br>");
document.writeln("                  </span> <font color=\"#FF0000\">");
document.writeln("				<span style=\"background-color: #FFFF00\">0尾</span></font><span style=\"color:#000\">【20.30】2尾【12.22】4尾【34.44】<br> ");
document.writeln("				  6尾【26.46】8尾【18.38】9尾【09.19】</span> <br>");
document.writeln("				  ");
document.writeln("              澳门开奖网 <span style=\"color: #0000FF\">91</span><span style=\"color:red\">5252</span><span style=\"color:#00f\">.com</span><span style=\"color:red\">全网至尊</span></p></td>");
document.writeln("            </tr>");
document.writeln("              <tr> ");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\"><span style=\"color:#00f\">112期</span>");
document.writeln("                <span style=\"color:red\">【⑥尾&#9323;码】</span>");
document.writeln("                <span style=\"color:#000\">开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">马21准</span></font><span style=\"color:#000\"> <br>");
document.writeln("                  0尾【20.40】</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">1尾</span></font><span style=\"color:#000\">【11.</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">21</span></font><span style=\"color:#000\">】5尾【05.25】<br> ");
document.writeln("				  6尾【16.46】8尾【18.38】9尾【09.49】</span> <br>");
document.writeln("				  ");
document.writeln("              澳门开奖网 <span style=\"color: #0000FF\">91</span><span style=\"color:red\">5252</span><span style=\"color:#00f\">.com</span><span style=\"color:red\">全网至尊</span></p></td>");
document.writeln("            </tr>");
document.writeln("              <tr> ");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\"><span style=\"color:#00f\">113期</span>");
document.writeln("                <span style=\"color:red\">【⑥尾&#9323;码】</span>");
document.writeln("                <span style=\"color:#000\">开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">马09准</span></font><span style=\"color:#000\"> <br>");
document.writeln("                  0尾【10.40】1尾【31.41】3尾【13.33】<br> ");
document.writeln("				  6尾【36.46】7尾【17.27】</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">9尾</span></font><span style=\"color:#000\">【39.49】</span> <br>");
document.writeln("				  ");
document.writeln("              澳门开奖网 <span style=\"color: #0000FF\">91</span><span style=\"color:red\">5252</span><span style=\"color:#00f\">.com</span><span style=\"color:red\">全网至尊</span></p></td>");
document.writeln("            </tr>");
document.writeln("              <tr> ");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\"><span style=\"color:#00f\">114期</span>");
document.writeln("                <span style=\"color:red\">【⑥尾&#9323;码】</span>");
document.writeln("                <span style=\"color:#000\">开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">鼠27准</span></font><span style=\"color:#000\"> <br>");
document.writeln("                  0尾【10.20】2尾【22.32】3尾【23.33】<br> ");
document.writeln("				  5尾【15.35】</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">7尾</span></font><span style=\"color:#000\">【17.</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">27</span></font><span style=\"color:#000\">】9尾【19.49】</span> <br>");
document.writeln("				  ");
document.writeln("              澳门开奖网 <span style=\"color: #0000FF\">91</span><span style=\"color:red\">5252</span><span style=\"color:#00f\">.com</span><span style=\"color:red\">全网至尊</span></p></td>");
document.writeln("            </tr>");
document.writeln("              <tr> ");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\"><span style=\"color:#00f\">115期</span>");
document.writeln("                <span style=\"color:red\">【⑥尾&#9323;码】</span>");
document.writeln("                <span style=\"color:#000\">开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">龙11准</span></font><span style=\"color:#000\"> <br>");
document.writeln("                  0尾【10.20】</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">1尾</span></font><span style=\"color:#000\">【</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">11</span></font><span style=\"color:#000\">.41】3尾【23.43】<br> ");
document.writeln("				  5尾【15.35】7尾【17.37】9尾【19.29】</span> <br>");
document.writeln("				  ");
document.writeln("              澳门开奖网 <span style=\"color: #0000FF\">91</span><span style=\"color:red\">5252</span><span style=\"color:#00f\">.com</span><span style=\"color:red\">全网至尊</span></p></td>");
document.writeln("            </tr>");
document.writeln("              <tr> ");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\"><span style=\"color:#00f\">118期</span>");
document.writeln("                <span style=\"color:red\">【⑥尾&#9323;码】</span>");
document.writeln("                <span style=\"color:#000\">开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">蛇34准</span></font><span style=\"color:#000\"> <br>");
document.writeln("                  0尾【10.20】3尾【03.33】</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">4尾</span></font><span style=\"color:#000\">【14.24】<br> ");
document.writeln("				  5尾【25.45】7尾【17.37】8尾【28.38】</span> <br>");
document.writeln("				  ");
document.writeln("              澳门开奖网 <span style=\"color: #0000FF\">91</span><span style=\"color:red\">5252</span><span style=\"color:#00f\">.com</span><span style=\"color:red\">全网至尊</span></p></td>");
document.writeln("            </tr>");
document.writeln("              <tr> ");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\"><span style=\"color:#00f\">119期</span>");
document.writeln("                <span style=\"color:red\">【⑥尾&#9323;码】</span>");
document.writeln("                <span style=\"color:#000\">开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">羊32准</span></font><span style=\"color:#000\"> <br>");
document.writeln("                  0尾【10.40】</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">2尾</span></font><span style=\"color:#000\">【22.</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">32</span></font><span style=\"color:#000\">】4尾【14.44】<br> ");
document.writeln("				  5尾【25.45】6尾【26.46】8尾【28.38】</span> <br>");
document.writeln("				  ");
document.writeln("              澳门开奖网 <span style=\"color: #0000FF\">91</span><span style=\"color:red\">5252</span><span style=\"color:#00f\">.com</span><span style=\"color:red\">全网至尊</span></p></td>");
document.writeln("            </tr>");
document.writeln("              <tr> ");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\"><span style=\"color:#00f\">120期</span>");
document.writeln("                <span style=\"color:red\">【⑥尾&#9323;码】</span>");
document.writeln("                <span style=\"color:#000\">开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">羊32准</span></font><span style=\"color:#000\"> <br>");
document.writeln("                  0尾【10.20】</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">2尾</span></font><span style=\"color:#000\">【12.22】3尾【33.43】<br> ");
document.writeln("				  5尾【25.35】7尾【07.17】8尾【18.38】</span> <br>");
document.writeln("				  ");
document.writeln("              澳门开奖网 <span style=\"color: #0000FF\">91</span><span style=\"color:red\">5252</span><span style=\"color:#00f\">.com</span><span style=\"color:red\">全网至尊</span></p></td>");
document.writeln("            </tr>");
document.writeln("              <tr> ");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\"><span style=\"color:#00f\">121期</span>");
document.writeln("                <span style=\"color:red\">【⑥尾&#9323;码】</span>");
document.writeln("                <span style=\"color:#000\">开：</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">兔36准</span></font><span style=\"color:#000\"> <br>");
document.writeln("                  0尾【10.40】2尾【12.42】4尾【14.44】<br> ");
document.writeln("				  5尾【25.35】</span><font color=\"#FF0000\"><span style=\"background-color: #FFFF00\">6尾</span></font><span style=\"color:#000\">【06.26】9尾【29.39】</span> <br>");
document.writeln("				  ");
document.writeln("              澳门开奖网 <span style=\"color: #0000FF\">91</span><span style=\"color:red\">5252</span><span style=\"color:#00f\">.com</span><span style=\"color:red\">全网至尊</span></p></td>");
document.writeln("            </tr>");
document.writeln("              <tr> ");
document.writeln("                <td align=\"center\" height=\"45\"><p style=\"line-height:200%\"><span style=\"color:#00f\">122期</span>");
document.writeln("                <span style=\"color:red\">【⑥尾&#9323;码】</span>");
document.writeln("                <span style=\"color:#000\">开：？00准 <br>");
document.writeln("                  0尾【10.20】1尾【11.41】4尾【04.44】<br> ");
document.writeln("				  5尾【25.35】6尾【06.26】7尾【27.47】</span> <br>");
document.writeln("				  ");
document.writeln("              澳门开奖网 <span style=\"color: #0000FF\">91</span><span style=\"color:red\">5252</span><span style=\"color:#00f\">.com</span><span style=\"color:red\">全网至尊</span></p></td>");
document.writeln("            </tr>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("            </tbody>");
document.writeln("");
document.writeln("");
document.writeln("        </table>");
document.writeln("");
document.writeln("");
document.writeln("        </div>");
document.writeln("");
document.writeln("");
document.writeln("</div>");
