//test 2022-5-17 dj2003 sy1
document.writeln("<div class=text-sy1>");
document.writeln("<table class=\"ggtables\" border=\"1\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" bordercolorlight=\"#FFFFFF\" bordercolordark=\"#FFFFFF\" bgcolor=\"#FFFFFF\" bordercolor=\"#e5e5e5\"><tbody><tr><td class=\"center f13 black l150\" bgcolor=\"#800000\">");
document.writeln("	<p align=\"center\">");
document.writeln("	<img src=\"https://cdn.jsdelivr.net/gh/doujiang2019/new@main/lwdj4o (1).jpg\"></td></tr><tr><td class=\"center f13 black l150\" height=\"33\">");
document.writeln("		<p align=\"center\">");
document.writeln("		<a target=\"_blank\" href=\"http://065858.com/#w1\" style=\"TEXT-DECORATION: none\" onfocus=\"undefined\">");
document.writeln("		<font color=\"#000000\" face=\"微软雅黑\"><b style=\"\"><font color=\"#0066ff\">全网最牛逼的</font></font><font color=\"#FF0000\" face=\"微软雅黑\"><span style=\"background-color: #FFFF00\">【三肖三码】</span></font><font color=\"#000000\" face=\"微软雅黑\">连中</font></b></a><font color=\"#000000\" face=\"微软雅黑\"><b style=\"\"><font color=\"#0066ff\">12期</font></b></font></td></tr><tr><td class=\"center f13 black l150\" height=\"33\">");
document.writeln("		<p align=\"center\">");
document.writeln("		<a target=\"_blank\" href=\"http://524848.com/#w1\" style=\"TEXT-DECORATION: none\" onfocus=\"undefined\">");
document.writeln("		<font color=\"#000000\" face=\"微软雅黑\"><b style=\"\"><font color=\"#ff0000\">");
document.writeln("		【一码中特】</font><font color=\"#ff00ff\">带彩民朋友们发家致富</font></b></font></a></td></tr><tr><td class=\"center f13 black l150\" height=\"33\">");
document.writeln("		<p align=\"center\">");
document.writeln("		<a target=\"_blank\" href=\"http://457272.com/#asy1\" style=\"TEXT-DECORATION: none\" onfocus=\"undefined\">");
document.writeln("		<font color=\"#ff3300\" face=\"微软雅黑\"><b>感恩</font><span style=\"background-color: #FFFF66\"><font face=\"微软雅黑\">【三中三】</font></span><font color=\"#ff3300\" face=\"微软雅黑\">,</font><font color=\"#FFFF00\" face=\"微软雅黑\"><span style=\"background-color: #FF0000\">650倍</span></font><font color=\"#ff3300\" face=\"微软雅黑\">大回馈</font></b></a></td></tr><tr><td class=\"center f13 black l150\" height=\"33\">");
document.writeln("		<p align=\"center\">");
document.writeln("		<a target=\"_blank\" href=\"http://964848.com/#w1\" style=\"TEXT-DECORATION: none\" onfocus=\"undefined\">");
document.writeln("		<font color=\"#000000\" face=\"微软雅黑\"><b>");
document.writeln("		<span style=\"color: rgb(255, 0, 0); background-color: rgb(255, 255, 0);\">");
document.writeln("		【两码中特】</span><span style=\"background-color: rgb(255, 255, 255);\"><font color=\"#0000ff\">带领大家上岸发财</font></span></b></font></a></td></tr><tr><td class=\"center f13 black l150\" height=\"33\">");
document.writeln("		<p align=\"center\">");
document.writeln("		<a target=\"_blank\" href=\"https://152323.com/#w1\" style=\"TEXT-DECORATION: none\" onfocus=\"undefined\">");
document.writeln("		<b style=\"background-color: rgb(255, 0, 255);\">");
document.writeln("		<font color=\"#FFCC00\" face=\"微软雅黑\">澳门顶尖出品史上最稳</font><font color=\"#FFFFFF\" face=\"微软雅黑\">【六肖中特】</font><font face=\"微软雅黑\" color=\"#000000\">40中36</font></b></a></td></tr><tr><td class=\"center f13 black l150\" height=\"33\">");
document.writeln("		<p align=\"center\">");
document.writeln("		<a target=\"_blank\" href=\"http://127272.com/#asy1\" style=\"TEXT-DECORATION: none\" onfocus=\"undefined\">");
document.writeln("		<font color=\"#000000\" face=\"微软雅黑\">");
document.writeln("		<span style=\"background-color: rgb(255, 255, 0);\">");
document.writeln("		<font color=\"#ff0000\" style=\"\"><b>澳门资讯【一组四连肖】连中五期</b></font></span></font></a></td></tr><tr><td class=\"center f13 black l150\" height=\"33\">");
document.writeln("		<p align=\"center\">");
document.writeln("		<a target=\"_blank\" href=\"http://662121.com/#w1    \" style=\"TEXT-DECORATION: none\" onfocus=\"undefined\">");
document.writeln("		<font color=\"#000000\" face=\"微软雅黑\"><b><font face=\"微软雅黑\">");
document.writeln("		<font color=\"#0000ff\">顶流【一肖一码】</font></font><font color=\"#FF0000\" face=\"微软雅黑\">十中七八</font><font color=\"#000000\" face=\"微软雅黑\">带各位吃香的喝辣的</font></font></b></a></td></tr><tr><td class=\"center f13 black l150\" height=\"33\">");
document.writeln("		<p align=\"center\">");
document.writeln("		<a target=\"_blank\" href=\"http://477878.com/#w1\" style=\"TEXT-DECORATION: none\" onfocus=\"undefined\">");
document.writeln("		<font color=\"#000000\" face=\"微软雅黑\"><b><font face=\"微软雅黑\">");
document.writeln("		<font color=\"#0000ff\">红姐最强</font></font><font color=\"#FFFF00\" face=\"微软雅黑\"><span style=\"background-color: #FF0000\">【六码中特】</span></font><font color=\"#ff0000\" face=\"微软雅黑\">连</font>中七期<font color=\"#ff0000\" face=\"微软雅黑\">正在</font><font color=\"#000000\" face=\"微软雅黑\">火爆</font><font color=\"#ff0000\" face=\"微软雅黑\">领取</font></font></b></a></td></tr></tbody></table>");
document.writeln("		");
document.writeln("		</div>");
document.writeln("		");
document.writeln("		<style>");
document.writeln("		");
document.writeln("		.text-sy1{");
document.writeln("  font-size:17pt;");
document.writeln("  font-weight:700;");
document.writeln("  text-transform:uppercase;");
document.writeln("  text-align:center;");
document.writeln("  margin:0 auto;");
document.writeln("  display:block;");
document.writeln("  position:relative}");
document.writeln("@keyframes animate{");
document.writeln("  0%{");
document.writeln("    opacity:.1}");
document.writeln("  100%{");
document.writeln("    opacity:1;");
document.writeln("    text-shadow:0 0 60px Red,0 0 15px orange,0 0 6px DarkRed}");
document.writeln("}");
document.writeln("@media only screen and (max-width:990px){");
document.writeln("  .text-sy1{");
document.writeln("    font-size:28px}");
document.writeln("}");
document.writeln("@media only screen and (max-width:767px){");
document.writeln("  .text-sy1{");
document.writeln("    font-size:28px}");
document.writeln("}");
document.writeln("@media only screen and (max-width:479px){");
document.writeln("  .text-sy1{");
document.writeln("    font-size:17px}");
document.writeln("}");
document.writeln("@media only screen and (max-width:359px){");
document.writeln("  .text-sy1{");
document.writeln("    font-size:15px}");
document.writeln("}");
document.writeln("		");
document.writeln("		</style>");